### ISSUE TITLE
Errors on the task of Node Classificaition

### ISSUE THREAD

**Issue by xuehansheng** [urielsinger/tNodeEmbed#1]
Hi,

Thank you for sharing your codes. However, when I run the task of node classification, it has some errors.

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    run(**params)
  File "main.py", line 17, in run
    tnodeembed = models.tNodeEmbed(graph_nx, task=task, dump_folder=dump_folder, test_size=test_size, **kwargs['n2vargs'])
  File "/home/xue/_Project/Dynamic Network Embedding/Code/tNodeEmbed-master/src/models/tNodeEmbed.py", line 49, in __init__
    self.graph_nx = self.initialize()
  File "/home/xue/_Project/Dynamic Network Embedding/Code/tNodeEmbed-master/src/models/tNodeEmbed.py", line 156, in initialize
    graph_nx = tNodeEmbed._align_embeddings(graph_nx, self.train_time_steps)
  File "/home/xue/_Project/Dynamic Network Embedding/Code/tNodeEmbed-master/src/models/tNodeEmbed.py", line 204, in _align_embeddings
    Q_t = np.array([node2Q_t[node] for node in node2Q_t_1])
  File "/home/xue/_Project/Dynamic Network Embedding/Code/tNodeEmbed-master/src/models/tNodeEmbed.py", line 204, in <listcomp>
    Q_t = np.array([node2Q_t[node] for node in node2Q_t_1])
KeyError: 111312

Thank you for your time and help.

**Comment by urielsinger** [comment]
It maybe because your pickle file is corrupted. Try deleting the cache file and running it again.

**Comment by xuehansheng** [comment]
@urielsinger Thank you for your reply. It works. But, Can you provide the detailed parameters of your paper? Because I cannot rerun the same outputs as your paper.

**Comment by urielsinger** [comment]
This repository is not a final version, and should not yet be relied upon.
I'm working these days on creating a final version.
