### ISSUE TITLE
Error: unexpected keyword argument 'nb_epoch'

### ISSUE THREAD

**Issue by tonygracious** [urielsinger/tNodeEmbed#7]
Can anyone explain me why this error occurring?
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    run(**params)
  File "main.py", line 28, in run
    tnodeembed.fit_generator(generator, steps_per_epoch, **keras_args)
  File "/home/tonygrey/tNodeEmbed/src/models/task_model.py", line 36, in fit_generator
    self.model.fit_generator(generator, steps_per_epoch, **keras_args)
TypeError: fit_generator() got an unexpected keyword argument 'nb_epoch'

**Comment by urielsinger** [comment]
Check your '_keras_' version.
In version 1.2.2 it's '_nb_epoch_' while in later versions it's '_epochs_'.
